# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

**Exercise 1.1 - Install NumPy**

In [4]:
!pip install numpy

**Exercise 1.2 - Import NumPy**

In [6]:
import numpy as np

**Exercise 1.3 - Example Usage and Execution**

In [8]:
data = np.array([1,2,3,4,5])

print(data)
print(len(data))
print(type(data))
print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


**Exercise 1.4 - All Exercises from the Lecture on NumPy**

In [10]:
arr = np.array([10, 20,
30, 40, 50])
print(arr)

[10 20 30 40 50]


In [11]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr)


[[10 20 30]
 [40 50 60]]


In [12]:
arr = np.array([10, 20, 30, 40])
print(arr[0])

10


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


In [14]:
arr = np.array([30, 20, 40, 10])
print(np.sort(arr))

[10 20 30 40]


In [15]:
arr = np.array(['kiwi', 'berry', 'pear'])
print(np.sort(arr))


['berry' 'kiwi' 'pear']


**Exercise 1.5 - Searching Arrays**

In [17]:
arr = np.array([3, 2, 14, 9, 10, 12])
indexes = np.where(arr == 9)          # The method:  where() - it found 3 as the index for value 9 in the array 
print(indexes)

(array([3], dtype=int64),)


**Exercise 1.6 - Join two arrays**

In [19]:
arr1 = np.array([9, 5, 8])
arr2 = np.array([55, 89, 76])

joined = np.concatenate((arr1, arr2))
print(joined)

[ 9  5  8 55 89 76]


**Exercise saved at github:  https://github.com/gitplants/AI240**